trigger:
- main

pool:
  vmImage: 'windows-latest' # Recomendado para pruebas de UI en Windows

steps:
# 1. Instalar el SDK de .NET
- task: UseDotNet@2
  displayName: 'Install SDK de .NET'
  inputs:
    packageType: 'sdk'
    version: '10.0.x' # Ajusta a la versión que uses

# 2. Restaurar dependencias de NuGet
- task: DotNetCoreCLI@2
  displayName: 'Restore Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 3. Compilar el proyecto
- task: DotNetCoreCLI@2
  displayName: 'Compile Project'
  inputs:
    command: 'build'
    projects: '**/*Test.csproj'
    arguments: '--configuration Release'

# 4. Ejecutar las pruebas con NUnit
- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    projects: '**/*Test.csproj'
    arguments: '--configuration Release --logger "nunit;LogFilePath=test-results/results.xml"'
    publishTestResults: false

# 5. Publicar pruebas
- task: PublishTestResults@2
  displayName: 'Publish Tests Result'
  condition: always()
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/results.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testRunTitle: 'NUnit Test Results'